services:
    postgres:
        image: postgres:15
        container_name: typetempo_db
        restart: always
        environment:
            POSTGRES_USER: typetempo
            POSTGRES_PASSWORD: typetempo
            POSTGRES_DB: typetempo
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    adminer:
        image: adminer:latest
        container_name: adminer
        restart: always
        ports:
            - "8080:8080"
        environment:
            ADMINER_DEFAULT_SERVER: postgres

volumes:
    postgres_data:
