name: typetempo
services:
    postgres:
        image: postgres:15
        container_name: typetempo-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: typetempo
            POSTGRES_PASSWORD: typetempo
            POSTGRES_DB: typetempo
        ports:
            - "${DOCKER_POSTGRES_PORT:-5432}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    adminer:
        image: adminer:latest
        container_name: typetempo-adminer
        restart: unless-stopped
        ports:
            - "${DOCKER_ADMINER_PORT:-8080}:8080"
        environment:
            ADMINER_DEFAULT_SERVER: postgres

volumes:
    postgres_data:
